
# Fix for Windows BLE constant Device Manager refresh.
# Windows doesn't always subscribe to GATT notifications properly;
# without this ZMK drops the connection and Windows reconnects in a loop.
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# FIXME not sure what these do or why they might be needed
#CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
#CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8
#CONFIG_INPUT_LOG_LEVEL_DBG=y

# Enable BLE HID support for layer status updates
# per https://github.com/maatthc/zmk-feature-appcompanion
# CONFIG_ZMK_LAYER_STATUS_BLE_HID=y
